# This workflow will build a .NET solution

name: Build .NET

on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      
jobs:
  build:
    name: Build .NET
    runs-on: windows-latest

    outputs:
      compile:

    steps:
    - name: Checkout
      uses: actions/checkout@v3
            
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore
      run: dotnet restore ${{ inputs.solutionFile }}
      
    - name: Build
      run: dotnet build ${{ inputs.solutionFile }} -c Release --nologo --no-restore