# This workflow will test a .NET solution
name: Build

on:
  workflow_call:
    inputs:
      dotnetVersion:
        required: true
        type: string
      configuration:
        required: true
        type: string
        default: "Release"
      projectFile:
        required: true
        type: string
      
jobs:
  test:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
          
    - name: Restore
      run: dotnet restore ${{ inputs.projectFile }}
      
    - name: Build
      run: dotnet build ${{ inputs.projectFile }} -c ${{ inputs.configuration }} --no-restore
