# This workflow will build a .NET solution

name: Build .NET

on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      
jobs:
  build:
    name: Build .NET
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
            
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore
      run: dotnet restore ${{ inputs.solutionFile }}
      
    - name: Build
      run: dotnet build ${{ inputs.solutionFile }} -c Release --nologo --no-restore -o './buildArtifacts'
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 'buildArtifacts'
        # A file, directory or wildcard pattern that describes what to upload
        path: './buildArtifacts'
        if-no-files-found: error
        retention-days: 7
