# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: Continuous Integration - Initialize

on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      artifactName:
        required: true
        type: string
        default: BuildArtifacts

jobs:
  init:
    strategy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
  
    - name: Restore
      run: dotnet restore ${{ inputs.solutionFile }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.artifactName }}
        path: Solution/*
        if-no-files-found: error
