# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: Continuous Integration

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request_target:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        dotnetVersion: [ '6.0' ]
        targetplatform: [ 'x64' ]
    
    runs-on: windows-latest
    
    env:
      ApplicationProjectPath: Solution\PackagedTestApp\PackagedTestApp\PackagedTestApp.csproj
      AppPackagesDirectory: AppPackages
      Configuration: Release
      SigningCertificate: GitHubActionsWorkflow.pfx
      SolutionPath: Solution\TestSolution.sln
      TestProjectPath: Solution\Domain.Test\Domain.Test.csproj
      WapProjectDirectory: Solution\PackagedTestApp\PackagedTestApp (Package)
      WapProjectPath: Solution\PackagedTestApp\PackagedTestApp (Package)\PackagedTestApp (Package).wapproj
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
  
    - name: Restore
      run: dotnet restore $env:SolutionPath
      
    - name: Test
      run: dotnet test $env:TestProjectPath -c $env:Configuration --no-restore
      
    - name: Build Application
      run: msbuild $env:ApplicationProjectPath /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration
      env:
        TargetPlatform: ${{ matrix.targetplatform }}
    
    - name: Restore Application
      run: msbuild $env:SolutionPath /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

    - name: Decode PFX
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODE_PFX }}")
        $currentDirectory = Get-Location
        $certificatePath = $env:SigningCertificate
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:SigningCertificate
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $certificatePath = Join-Path -Path Solution -ChildPath $env:SigningCertificate
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $certificatePath = Join-Path -Path Solution\PackagedTestApp -ChildPath $env:SigningCertificate
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $certificatePath = Join-Path -Path $env:WapProjectDirectory -ChildPath $env:SigningCertificate
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
    
    #- name: Decode PFX
      #run: |
        #echo $CERTIFICATE_BASE64 | base64 --decode > $env:SigningCertificate
      #shell: bash
      #env:
          #CERTIFICATE_BASE64: ${{ secrets.BASE64_ENCODE_PFX }}
    
    - name: Build package
      #run: msbuild $env:WapProjectPath /p:Configuration=$env:Configuration /p:Platform=$env:TargetPlatform /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      run: msbuild $env:SolutionPath /p:Configuration=$env:Configuration /p:Platform=$env:TargetPlatform /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.PFX_KEY }} -verbosity:minimal
      env:
        #AppxBundle: Always
        #BuildMode: SideloadOnly
        TargetPlatform: ${{ matrix.targetplatform }}
        
    - name: Remove PFX
      run: Remove-Item -path $env:WapProjectDirectory/$env:SigningCertificate
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MSIX Package
        path: ${{ env.WapProjectDirectory }}\${{ env.AppPackagesDirectory }}
