# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: Continuous Integration

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request_target:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        dotnetVersion: [ '6.0' ]
        targetplatform: [ 'x64' ]
    
    runs-on: windows-latest
    
    env:
      ApplicationProjectPath: Solution\PackagedTestApp\PackagedTestApp\PackagedTestApp.csproj
      AppPackagesDirectory: AppPackages
      Configuration: Release
      SolutionPath: Solution\TestSolution.sln
      TestProjectPath: Solution\Domain.Test\Domain.Test.csproj
      WapProjectPath: Solution\PackagedTestApp\PackagedTestApp (Package)\PackagedTestApp (Package).wapproj
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
  
    - name: Test Domain
      run: dotnet test $env:TestProjectPath -c $env:Configuration
    
    - name: Restore application
      run: msbuild $env:SolutionPath /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        RuntimeIdentifier: win10-${{ matrix.targetplatform }}
