# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: Continuous Integration

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request_target:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [ 'x86', 'x64' ]
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        dotnet_version: '6.x'
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
