# This workflow will deploy a .NET project

name: Deploy .NET

on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      
jobs:
  deploy:
    name: Deploy .NET
    runs-on: windows-latest
    
    steps:      
    - name: Deploy
      run: echo 'Prouduction deployment of ${{ inputs.solutionFile }}...'
