# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  SOLUTION_PATH: "Solution/TestSolution.sln"

jobs:
  setup:
    name: Setup

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION_PATH
      
  build:
    name: Build
    needs: setup

    runs-on: windows-latest
    
    steps:
    - name: Build
      run: dotnet build $env:SOLUTION_PATH -c Release --nologo --no-restore
      
  test:
    name: Test
    needs: build

    runs-on: windows-latest
      
    steps:
    - name: Test
      run: dotnet test $env:SOLUTION_PATH -c Release --nologo --no-build --verbosity normal
