# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ "Release" ]
        platform: [ "x86", "x64" ]

    runs-on: windows-latest
    
    env:
      SolutionName: "Solution/TestSolution.sln"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore $env:SolutionName
      
    - name: Build
      run: dotnet build $env:SolutionName --nologo --no-restore -c $env:Configuration -a $env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
      
    - name: Test
      run: dotnet test $env:SolutionName --nologo --no-build --verbosity normal -c $env:Configuration -a $env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
