# This workflow will build a .NET solution

name: Build .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  SolutionName: "Solution/TestSolution.sln"
      
jobs:
  build:
    name: Build .NET
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
            
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore
      run: dotnet restore $env:SolutionName
      
    - name: Build
      run: dotnet build $env:SolutionName -c Release --nologo --no-restore
    
    - name: Test
      run: dotnet test $env:SolutionName -c Release --nologo --no-build --verbosity normal

  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
