# This workflow will build a .NET solution

name: Overall .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
      
jobs:      
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/test.net.yml
    strategy:
      matrix:
        dotnet: [ "6.0", "7.0" ]
        configuration: [ "Release" ]
    secrets: inherit
    with:
      solutionFile: "Solution/TestSolution.sln"
      dotnetVersion: ${{ matrix.dotnet }}
      configuration: ${{ matrix.configuration }}
