# This workflow will build a .NET solution

name: Overall .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
      
jobs:      
  call-build-n-test-workflow:
    name: Build & Test
    uses: ./.github/workflows/build&test.net.yml
    secrets: inherit
    with:
      solutionFile: "Solution/TestSolution.sln"
      dotnetVersion: "6.0"
      configuration: "Release"
