# This workflow will build a .NET solution

name: Overall .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  SolutionFile: "Solution/TestSolution.sln"
      
jobs:
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/test.NET.yml
    secrets: inherit
    with:
      solutionFile: "Solution/TestSolution.sln"
      
  call-build-workflow:
    name: Build
    needs: call-test-workflow
    uses: ./.github/workflows/build.NET.yml
    secrets: inherit
    with:
      solutionFile: "Solution/TestSolution.sln"

  call-deploy-workflow:
    name: Deploy
    needs: call-build-workflow
    uses: ./.github/workflows/deploy.NET.yml
    secrets: inherit
