# This workflow will test a .NET solution

name: Test .NET

on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      
jobs:
  test:
    name: Test .NET
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
            
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Download artifacts
      uses: actions/download-artifact@v3
      #with:
        #name: BuildArtifacts

    - name: Test
      run: dotnet test ${{ inputs.solutionFile }} -c Release --nologo --no-build --verbosity normal
