# This workflow will build a .NET solution
name: Test orchestrator

on:
  push:
    branches: [ "develop" ]
  pull_request_target:
    branches: [ "master", "develop" ]
      
jobs:      
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/testCore.yml
    strategy:
      matrix:
        dotnet: [ "6.0", "7.0" ]
        configuration: [ "Release" ]
        testProjectFile: [
          "Solution/Domain.Test/Domain.Test.csproj"
        ]
    secrets: inherit
    with:
      dotnetVersion: ${{ matrix.dotnet }}
      configuration: ${{ matrix.configuration }}
      projectFile: ${{ matrix.testProjectFile }}
